#!/bin/bash

DOCKER_USER=19037626d

dep ensure -v
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o lxcfs-admission-webhook
docker build --no-cache -t ${DOCKER_USER}/lxcfs-admission-webhook:v1 .
rm -rf lxcfs-admission-webhook

docker push ${DOCKER_USER}/lxcfs-admission-webhook:v1
