#!/bin/bash

DOCKER_USER=19037626d

CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -a -installsuffix cgo -o lxcfs-admission-webhook ./src
docker build --no-cache -t ${DOCKER_USER}/lxcfs-admission-webhook:v1 .
rm -rf lxcfs-admission-webhook

docker push ${DOCKER_USER}/lxcfs-admission-webhook:v1
